SRCDIR = .
DESTDIR = 
prefix = /usr/local
exec_prefix = ${prefix}
bindir = ${exec_prefix}/bin
libdir = ${exec_prefix}/lib
includedir = ${prefix}/include
CC = gcc
AR = ar
LD = gcc
RANLIB = ranlib
STRIP = strip
STATICLIBNAME = liblsmash.a
STATICLIB = liblsmash.a
SHAREDLIBNAME = liblsmash.so.2
SHAREDLIB = 
IMPLIB = 
CFLAGS = -Os -ffast-math -g -Wshadow -Wall -std=c99 -pedantic -I. -I. -g -ggdb -fexcess-precision=fast
LDFLAGS = -g -L. 
SO_LDFLAGS = 
LIBS = -lm 
LIBARCH = 
DEFNAME = 
SLIB_CMD = 
SRCS =  common/alloc.c common/bits.c common/bytes.c common/list.c common/multibuf.c common/osdep.c common/utils.c codecs/a52.c codecs/alac.c codecs/description.c codecs/dts.c codecs/h264.c codecs/hevc.c codecs/id.c codecs/mp4sys.c codecs/mp4a.c codecs/mp4v.c codecs/nalu.c codecs/qt_wfex.c codecs/vc1.c codecs/wma.c importer/a52_imp.c importer/adts_imp.c importer/als_imp.c importer/amr_imp.c importer/dts_imp.c importer/importer.c importer/isobm_imp.c importer/mp3_imp.c importer/nalu_imp.c importer/vc1_imp.c importer/wave_imp.c core/box.c core/box_default.c core/box_type.c core/chapter.c core/file.c core/fragment.c core/isom.c core/meta.c core/print.c core/read.c core/summary.c core/timeline.c core/write.c
SRC_TOOLS =  cli/harness.c cli/cli.c cli/muxer.c cli/remuxer.c cli/boxdumper.c cli/timelineeditor.c
TOOLS_ALL = h muxer remuxer boxdumper timelineeditor
TOOLS =  cli/h cli/muxer cli/remuxer cli/boxdumper cli/timelineeditor
MAJVER = 2
